app = "${APP_NAME}"
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'n8n_data'
  destination = '/home/node/data'

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[http_service.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

[[services]]
  protocol = ''
  internal_port = 5678

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

    [services.ports.tls_options]
      versions = ['TLSv1.2', 'TLSv1.3']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
